import Footer from "@/components/Footer";
import Header from "@/components/Header/Header";
import Nav from "@/components/Nav";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <Header />

          <div className="flex justify-between items-center">
            <Nav className="w-1/3" />

            {children}
          </div>
        </div>

        <Footer />
      </body>
    </html>
  );
}
