import Footer from "@/components/Footer";
import Header from "@/components/Header/Header";
import Nav from "@/components/Nav";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <div className=" flex-1 flex flex-col">
          <Header />

          <div className="flex-1 flex justify-center items-stretch ">
            <div className="w-[90%] h-auto flex justify-between items-strech border">
              <Nav className="w-1/3 flex justify-center items-center" />

              <div className="w-1/2 h-auto">{children}</div>
            </div>
          </div>
        </div>

        <Footer />
      </body>
    </html>
  );
}
